In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4]
a = np.array(list1)
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [4]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
s = " Data-Science, FTW!! "
s_lower = s.lower()
print(s_lower)

 data-science, ftw!! 


In [7]:
import numpy as np
np.__version__

'1.23.5'

In [8]:
s_clean1 = s_lower.strip()
print(s_clean1)

data-science, ftw!!


In [9]:
s_clean2 = s_lower.strip("-,!")
print(s_clean2)

 data-science, ftw!! 
